### PR TITLE
Consul implementation

### PR DESCRIPTION
**Pull request by thiagoloureiro**
I created an implementation for Consul, with Unit Tests and Functional Tests

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @thiagoloureiro 

I merged this PR but, probably I do more work than necessary. Please for next PR:

- the csproj properties are variables defined on dependencies.props, please checkout other csproj.
- If you create a new healthcheck / package please use dependencies.props to set versions
- I added IHttpClientFactory support instead static Httpclient
- I added support for HTTPS connections

Thansk again!

**Comment by thiagoloureiro** [comment]
@unaizorrilla  sure thing, It was my first PR here, understood! thanks!!

**Comment by thiagoloureiro** [comment]
@CarlosLanderas @unaizorrilla  

guys any plan to release the nuget package? for this feature.

**Comment by unaizorrilla** [comment]
On nuget https://www.nuget.org/packages/AspNetCore.HealthChecks.Consul/

**Comment by thiagoloureiro** [comment]
> On nuget https://www.nuget.org/packages/AspNetCore.HealthChecks.Consul/

¡muchas gracias!

**Pull request merged**
