### PR TITLE
Add livenessName to notification callback functions

### PR DESCRIPTION
**Pull request by JGud007**
**What this PR does / why we need it**: Adds the liveness name to the custom notification functions to increase customizability of notifications.

**Which issue(s) this PR fixes**:  This is a partial solution to #1114. I think that the functions can be further improved but this is a first step that will increase the ability to customise the custom notifications.

Please reference the issue this PR will close: #1114 

**Does this PR introduce a user-facing change?**: No

### CODE REVIEW

**Comment by sungam3r** [comment]
@carlosrecuero I'm fine with that change though techically it's breaking.

**Review by sungam3r — APPROVED** [review]

**Comment by sungam3r** [comment]
Breaking change will be observable after #1175.

**Comment by sungam3r** [comment]
@JGud007 Please update branch with change from `master`. I merged #1175 so you can check API changes.

**Comment by JGud007** [comment]
@sungam3r Merged with master without issues. Had one comment on your previous PR that I noticed https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1175#discussion_r882076755

**Comment by sungam3r** [comment]
Ah, API approval test for UI project is disabled for now.

**Comment by sungam3r** [comment]
Waiting 2-3 days for comments from @carlosrecuero . @JGud007 ping me to merge after.

**Comment by sungam3r** [comment]
No comments so I merge it.

**Comment by xtomino** [comment]
Thank you for this PR. When will the new NuGet version of AspNetCore.HealthChecks.UI be released?

**Comment by sungam3r** [comment]
ping @carlosrecuero. I did not publish UI packages yet.

**Comment by sungam3r** [comment]
After 7 commits into master to fix CI issues, reading docs [like this one](https://github.com/dotnet/sdk/issues/12981) and jumping around adding/removing git tags I managed to publish UI packages
https://www.nuget.org/packages?q=AspNetCore.healthchecks.UI

**Pull request merged**
