### PR TITLE
Add Azure KeyVault cryptographic keys check

### PR DESCRIPTION
**Pull request by Riff451**
Hi, this a proposed PR to slightly extend the already existing `HealthChecks.AzureKeyVault` created with PR #19 .
The idea is to support the check also for the cryptographic keys that can be stored in KeyVault. I noticed that another user suggested the change in the above PR, but I couldn't find any ongoing work.

Usage:

Default usage with Managed Service Identity:

```csharp
services.AddHealthChecks()
    .AddAzureKeyVault(setup =>
    {
        setup
            .UseKeyVaultUrl("https://[vaultname].vault.azure.net/")                  
            .AddKey("keyname");
    });
```

Usage usage client id and client secret:

```csharp
services.AddHealthChecks()
    .AddAzureKeyVault(setup =>
    {
        setup
            .UseKeyVaultUrl("https://[vaultname].vault.azure.net/")    
            .UseClientSecrets("clientid", "clientsecret")
            .AddKey("keyname");
    });
```

Thanks.

### CODE REVIEW

**Comment by CarlosLanderas** [comment]
Thanks @Riff451, let me test it and I'll merge it

**Comment by CarlosLanderas** [comment]
Tested and working. Thanks for the PR @Riff451

**Comment by CarlosLanderas** [comment]
Adding certificates feature as well:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/369

**Comment by Riff451** [comment]
Thanks @CarlosLanderas for the quick review and for the new certificates feature as well :)

**Pull request merged**
