### PR TITLE
Add package for SurrealDB

### PR DESCRIPTION
**Pull request by Odonno**
**What this PR does / why we need it**:

Add a new HealthChecks package to support the [SurrealDB](https://surrealdb.com/) database.

**Special notes for your reviewer**:

N/A

**Does this PR introduce a user-facing change?**:

N/A

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [x] Created/updated tests
- [x] Unit tests passing
- [x] End-to-end tests passing

### CODE REVIEW

**Comment by Odonno** [comment]
Anything else required? @unaizorrilla

**Comment by sungam3r** [comment]
@Odonno thanks. I help to support this project but was away from it for ~6 months. I'll review ASAP.

**Comment by Odonno** [comment]
> @Odonno thanks. I help to support this project but was away from it for ~6 months. I'll review ASAP.

Ah, nice to see! I made some improvements. Should be ok now.

**Comment by Odonno** [comment]
Maybe one day 🤣

**Review by adamsitnik — APPROVED** [review]
@Odonno big thanks for your contribution!

The PR was stale for a long time due to lack of review, so I decided to spent some of my time and solve the merge conflicts, fix the build and apply the suggestions I had. I hope you don't mind.

**Comment by Odonno** [comment]
Hello @adamsitnik 

I wasn't expecting this today. Thank you for merging this PR. I will check later if some adjustments are needed.

**Pull request merged**
