### PR TITLE
Syntax issues and refactoring

### PR DESCRIPTION
**Pull request by alicommit-malp**
**What this PR does / why we need it**:
Better code readability 

**Which issue(s) this PR fixes**:
some syntax issues and refactoring 

Please reference the issue this PR will close: #_[issue number]_

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: no

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [ ] Created/updated tests
- [x] Unit tests passing
- [ ] End-to-end tests passing
- [x] Extended the documentation
- [ ] Provided sample for the feature

### CODE REVIEW

**Comment by sungam3r** [comment]
@alicommit-malp Please rebase onto `master` if you are goint to continue work on this PR. I think that a lot of your changes are already in `master`.

**Comment by sungam3r** [comment]
ping @alicommit-malp

**Comment by alicommit-malp** [comment]
Hi :) i will look into it

**Comment by sungam3r** [comment]
@alicommit-malp Thanks for your contribution. From the moment of your last commit, the `master` has gone far ahead with many code-style fixes. I close this PR for now.

**Pull request closed without merging**
