### PR TITLE
Code cleanup 2

### PR DESCRIPTION
**Pull request by sungam3r**
Relates to #162 , second part - reorganize unit test code and remove copy-paste.

### CODE REVIEW

**Comment by sungam3r** [comment]
This time I removed all the blank lines between the methods.

**Comment by sungam3r** [comment]
I also noticed that recently added `CloudFirestoreHealthCheck` use `IAsyncEnumerator`, but does not call `Dispose` on it. Is this done intentionally?

**Comment by unaizorrilla** [comment]
Let me check!

**Comment by unaizorrilla** [comment]
Fixed on recently commit,

**Comment by unaizorrilla** [comment]
> 
> 
> This time I removed all the blank lines between the methods.

:-) .. @sungam3r  I need some time to merge this PR,  thanks for contribute again!

**Comment by CarlosLanderas** [comment]
As all asre cleanups and minor changes, please Squash the 9 commits in a single one. Thanks

**Comment by sungam3r** [comment]
> As all asre cleanups and minor changes, please Squash the 9 commits in a single one. Thanks

Is this comment addressed to me or to @unaizorrilla ?

**Comment by CarlosLanderas** [comment]
@sungam3r is addressed to you :). Thanks

**Comment by sungam3r** [comment]
It seemed to me that this is a [built-in GitHub function](https://help.github.com/en/articles/about-pull-request-merges#squash-and-merge-your-pull-request-commits) for merging pull request.

**Pull request closed without merging**
