### PR TITLE
#251 Enhancements to UI for refresh interval

### PR DESCRIPTION
**Pull request by danielearwicker**
- configuration now includes `ClientOptions`, whole object injected into UI via variable replacement in `index.html`
- separate component `PollingInterval` takes care of appearance and validation for this feature. 'Change' button enables/highlights when there is something valid/different for it to apply, makes it a bit more intuitive.
- `ClientOptions` includes `HidePollingIntervalControl` - if set the polling interval controls don't appear and `DefaultPollingIntervalSeconds` is used.
- using `window.setInterval` avoids type error as TS gets confused between browser and node return types for global `setInterval`

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @CarlosLanderas 

Can you check this?

**Comment by unaizorrilla** [comment]
Bump @CarlosLanderas

**Comment by CarlosLanderas** [comment]
Hello folks. We are working in UI 2.0
@evacrespo forked the repository and is working on it  right now
I'm gonna create a branch so we can integrate her work and review this PR towards that bramch

**Comment by shep1987** [comment]
Have updated the styles to match the UI 2.0

Here is a snip of the disabled style of the button.
image

Please let us know if there is anything else.

**Comment by shep1987** [comment]
@unaizorrilla @CarlosLanderas 

Hey, 
I understand we are all busy at this time but any feedback on this PR?

Would be great to have it merged or know what we need to change to get it merged.

Thanks

**Comment by CarlosLanderas** [comment]
Hello @shep1987 . I am about to finish my holidays and I will try to merge this. There are quite some changes so I will have to test it carefully. Some fixes where introduces to the UI some months ago, could you try to merge master into this branch to see that everything works correctly?. I think the changes won't affect you btw.

**Comment by shep1987** [comment]
Thanks Carlos,

We have re-based since the original PR due to some of the changes you mentioned so i think we caught everything, have merged in master as requested.

Enjoy the rest of your holiday!

**Comment by CarlosLanderas** [comment]
Closing this PR. Due to security considerations the interval is now configured in the backend

**Pull request closed without merging**
