### PR TITLE
[RabbitMQ] Using SslOptions if passed in

### PR DESCRIPTION
**Pull request by rwkarg**
Addresses #324 
This change will use the IConnectionFactory as configured or the generated ConfigurationFactory with specified SslOption set when creating a connection.

### CODE REVIEW

**Comment by rwkarg** [comment]
@unaizorrilla

**Comment by unaizorrilla** [comment]
Hi @rwkarg 
PR is merged !! thanks for contribute on this!

Release build is on appveyor, when finished, a new package with version 3.0.2 will be on NuGet

**Comment by bkaid** [comment]
Upgrading from 3.0.1 to 3.0.2 without SSL turned now passes a null SslOption object and causes a null reference exception in the RabbitMQ client library, when previously a `new SslOption()` ended up getting passed by virtue of not setting ConnectionFactory.Ssl.  Probably doing
```
Ssl = sslOption ?? new SslOption()
```
would have been better to not cause breaking changes and forcing an SslOption to be passed in.

**Comment by unaizorrilla** [comment]
Hi @bkaid 

Thanks for catch this, i pushed a new commit to solve this issue, when release build finished a new package 3.0.3 will be available and solve this issue.
thanks

**Comment by bkaid** [comment]
Confirmed that 3.0.3 fixed it, thanks!

**Pull request merged**
