### PR TITLE
Fix bug with regression of datetime string in OnStateFrom column in UI

### PR DESCRIPTION
**Pull request by BoSoeborgPetersen**
Which issue(s) this PR fixes: #835 

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [X] Code compiles correctly
- [ ] Created/updated tests
- [ ] Unit tests passing
- [ ] End-to-end tests passing
- [ ] Extended the documentation
- [ ] Provided sample for the feature

### CODE REVIEW

**Comment by BoSoeborgPetersen** [comment]
Could someone please have a look?

**Comment by sungam3r** [comment]
@BoSoeborgPetersen Hi. I help to maintain this repo for some time. I have never used UI stuff from this repo so feedback from core team is required here. Ping @carlosrecuero @unaizorrilla . Anyway I see conflicts now.

**Comment by BoSoeborgPetersen** [comment]
Well, a lot happens in 15 months,. Anyway if this is the current state of this project, then what is the point in trying to fix anything.

**Comment by sungam3r** [comment]
@BoSoeborgPetersen I do the best I can. I'm fine to merge if/when you resolve conflicts and CI passes.

**Comment by sungam3r** [comment]
Superseded by #1880. Thanks, @BoSoeborgPetersen .

**Pull request closed without merging**
