### PR TITLE
fix: display "collections not found" text correctly

### PR DESCRIPTION
**Pull request by Odonno**

### CODE REVIEW

**Comment by Odonno** [comment]
Hi @unaizorrilla 

I just tested the Health Checks for Cloud Firestore. It works really well but it seems I missed one thing when the "collections not found" error happened. The text is not displayed correctly.

Thank you.

**Comment by unaizorrilla** [comment]
Merged, a new version 2.2.0-preview-2-beta19 will be on nuget when release build finish!

Thanks!

**Comment by Odonno** [comment]
And now it works like a charm. Thank you!

**Comment by Odonno** [comment]
Just for you to notice but if you check the nuget website, `2.2.0-preview-2-beta19` is a previous version of `2.2.0-preview-beta19`. It is so because "version number" are not based on uploaded date but on the version name.

**Pull request merged**
