### PR TITLE
ability to setup settings

### PR DESCRIPTION
**Pull request by AlexandruRus23**
I wanted to be able to configure the healthchecks in an application where I install the UI nuget package.

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @AlexandruRus23 

Can you explain with more details which scenario you want to cover?

**Comment by AlexandruRus23** [comment]
Hi @unaizorrilla 

I'm running Azure Service Fabric which allocates application ports dynamically between 20000 and 30000. I'm also running Traefik as a reverse proxy. I am able to invoke Traefik's api in order to get the services' Urls and healthcheck options (virtual path of the healtcheck endpoint). 

I would like to build an application hosting the Healthchecks UI via the nuget package where I pool Traefik's api in order to get the right Urls where I should perform the healthchecks. Unfortunately the static file configuration is not enough for this.

**Comment by CarlosLanderas** [comment]
@AlexandruRus23 , I would say it would be better to bind first from configured settings and then extend with desired configuration

Instead of:

```csharp
   setupSettings?.Invoke(healthCheckSettings);
   configuration.Bind(Keys.HEALTHCHECKSUI_SECTION_SETTING_KEY, healthCheckSettings);
```

I think is better

```csharp
   configuration.Bind(Keys.HEALTHCHECKSUI_SECTION_SETTING_KEY, healthCheckSettings);
   setupSettings?.Invoke(healthCheckSettings);

```

**Comment by unaizorrilla** [comment]
Hi @AlexandruRus23 

I try to review this soon, thanks for contributing.

**Comment by unaizorrilla** [comment]
Merged, thanks for contributing @AlexandruRus23

**Comment by AlexandruRus23** [comment]
Hi @unaizorrilla
Thank you and cheers!

**Comment by unaizorrilla** [comment]
Please, check if all is ok for you!

**Pull request merged**
