### PR TITLE
Use webpack5 syntax to include woff2 in bundle and remove url-loader

### PR DESCRIPTION
**Pull request by markmonster**
**What this PR does / why we need it**:
This PR will fix the #2130 . The real developer of this PR is actually #2133 but this somehow got stuck in merging. That's why I tried to get the administrative process going after almost 5 months. The credits should go to [schulz3000](https://github.com/schulz3000).

**Which issue(s) this PR fixes**: #2130

**Special notes for your reviewer**:
Use webpack5 syntax to include woff2 in bundle and remove url-loader that's no longer in use.

**Does this PR introduce a user-facing change?**:
It will reinstate the icons that got lost with a previous change.

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [x] Unit tests passing
- [x] End-to-end tests passing

### CODE REVIEW

**Comment by markmonster** [comment]
@dotnet-policy-service agree

**Comment by markmonster** [comment]
@sungam3r do you know how I can ping the maintainer to look at this PR? Thanks.

**Comment by Jamie-Clayton** [comment]
I've tested this solution locally and it resolved a range of issues that have been floated around v8.x of the health check UIs.

HealthChecks-EndToEnd-PR2217

LGTM

**Review by Jamie-Clayton — APPROVED** [review]

**Review by rob-baldwin — APPROVED** [review]

**Comment by Jamie-Clayton** [comment]
@unaizorrilla - Would you have time to review some of these PR's, please? Gracias

**Comment by Jamie-Clayton** [comment]
@Alirexaa this would be a good inclusion in v8.1

**Review by iploooox — APPROVED** [review]

**Comment by benjaminoerskov** [comment]
@markmonster Any idea when this can be released?

**Comment by markmonster** [comment]
> @markmonster Any idea when this can be released?

I have no idea at all. This is managed by the maintainers of this project. I hope it can be released soon.

**Comment by danmajgaard** [comment]
This was released by 2024-08-29 with AspNetCore.HealthChecks.UI version 8.0.2

(not by me, im just a user of the package :) )

**Pull request merged**
