### PR TITLE
upgrade library Microsoft.Data.SqlClient to 5.1.3

### PR DESCRIPTION
**Pull request by MvarelaWoffu**
Upgrade library Microsoft.Data.SqlClient to 5.1.3

Unprotected Storage of Credentials:

https://security.snyk.io/vuln/SNYK-DOTNET-MICROSOFTDATASQLCLIENT-6149434?_gl=1%2a18o7lyo%2a_ga%2aMTY2ODkxNDQwMy4xNjkwMzc5NzE0%2a_ga_X9SH3KP7B4%2aMTcwNTAwNTQ1Mi4xMzUuMS4xNzA1MDA2MjUyLjAuMC4w

### CODE REVIEW

**Comment by MvarelaWoffu** [comment]
@dotnet-policy-service agree

**Comment by ThumbGen** [comment]
5.1.4 was released meanwhile...

**Review by thompson-tomo — APPROVED** [review]

**Comment by deathchurch** [comment]
Can Microsoft.Data.SqlClient be upgraded to v5.2.1? Version 5.2.0 is also bringing in Azure.Core.1.35.0 and Azure.Identity.1.10.3 which is also being flagged by IQ Server as needing to be upgraded.

**Comment by pteeninga** [comment]
> Can Microsoft.Data.SqlClient be upgraded to v5.2.1? Version 5.2.0 is also bringing in Azure.Identity.1.10.3 which is also being flagged by SQL Server as needing to be upgraded.

In addition, version 5.2.0 introduced a bug, which code change is reverted in version 5.2.1. This bug is causing issues when using redirect connection policy for SQL Sever. And also other connection issues, for example: https://github.com/dotnet/SqlClient/issues/2385.

So could indeed the version be updated to 5.2.1 for Microsoft.Data.SqlClient?

**Comment by Alirexaa** [comment]
close this as completed via #2183

**Pull request closed without merging**
