### PR TITLE
UI - Escape all webhook payload fields

### PR DESCRIPTION
**Pull request by CarlosLanderas**
**What this PR does / why we need it**:

This PR has not been addreesed  #219, so I am creating a new one to fix the webhooks payload problem.

### CODE REVIEW

**Comment by CarlosLanderas** [comment]
@enthiric, could you test your project with this changes?. Apart from receiving the notifications, can you list see the webhooks displayed in their section?

**Comment by enthiric** [comment]
Hi, sorry for the late response. I'll validate this tomorrow and get back to you.

**Comment by enthiric** [comment]
@CarlosLanderas the changes fixed the issue. 

The payload now contains the correctly encoded message: 
`{"text":"[HEALTH CHECK] [DEVELOPMENT] basic is FAILING - Reason: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : \"1\", ConnectionMode : \"Automatic\", Type : \"Standalone\", State : \"Disconnected\", Servers : [{ ServerId: \"{ ClusterId : 1, EndPoint : \"Unspecified/localhost:27017\" }\", EndPoint: \"Unspecified/localhost:27017\", State: \"Disconnected\", Type: \"Unknown\", HeartbeatException: \"MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.\n ---\u003e System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (61): Connection refused [::1]:27017\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\n   at System.Net.Sockets.Socket.\u003c\u003ec.\u003cConnectAsync\u003eb__274_0(IAsyncResult iar)\n--- End of stack trace from previous location where exception was thrown ---\n   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)\n   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)\n   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)\n   --- End of inner exception stack trace ---\n   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)\n   at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)\", LastUpdateTimestamp: \"2020-05-19T08:31:43.7270920Z\" }] }. - See interface for more details.","channel":"#health-checks-test","link_names": 1,"username":"The steamster","icon_emoji":":man_in_steamy_room:"}`

Also furthermore it's now being shown by slack within their interface (meaning the webhook no longer breaks as it did before):
image

**Comment by CarlosLanderas** [comment]
@enthiric thanks for the feedback. I feel more confident to merge this as I have been busy and did not have the time to setup slack webhooks to test it. I'll prepare a release for this this afternoon :)

**Comment by enthiric** [comment]
@CarlosLanderas No worries! Thank you for continuing with the work that the original author started.

**Comment by CarlosLanderas** [comment]
Fixing branch conflicts and ready to merge. This changes will be available in next UI release

**Pull request merged**
