### PR TITLE
Added EventStore to Build status overview

### PR DESCRIPTION
**Pull request by NielsPilgaard**
**What this PR does / why we need it**:
Adds build status information about EventStore to the README

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

No

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [ ] Created/updated tests
- [ ] Unit tests passing
- [ ] End-to-end tests passing
- [x] Extended the documentation
- [ ] Provided sample for the feature

### CODE REVIEW

**Comment by NielsPilgaard** [comment]
Somewhat unrelated, but how does the release flow work? Should I request a new release for the EventStore package, or submit the tag somehow?

**Review by sungam3r — APPROVED** [review]

**Comment by sungam3r** [comment]
One with write access to this repo pushes a tag with name like `release-eventstore-6.0.3` that triggers cd pipeline. Then build process takes version from dependencies.props, builds desired project, packs it and pushes to nuget.org. Recently, I have been engaged in the publishing of releases at the request of devs.

**Comment by NielsPilgaard** [comment]
In that case, I would like to request that you push a tag with the name `release-eventstore-6.0.2`, please 😃

**Comment by sungam3r** [comment]
https://www.nuget.org/packages/AspNetCore.HealthChecks.EventStore/6.0.2

**Comment by NielsPilgaard** [comment]
Thank you :)

**Pull request merged**
