### PR TITLE
Add support to specify the database to check for existence

### PR DESCRIPTION
**Pull request by tiesmaster**
**What this PR does / why we need it**:
This adds support to health check for the CosmosDB database, if specified on the health check configuration.

**Which issue(s) this PR fixes**:
#558: Add support in the CosmosDB health check to check database / collection is present 

**Special notes for your reviewer**:
I didn't encounter any functional tests for the CosmosDB health check. I see that for the other functional tests docker containers are being used, however, [the emulator is not yet available in Linux](https://feedback.azure.com/forums/263030/suggestions/18533509), and hence Docker. I've created a console app to test it (see [my other branch](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/compare/master...tiesmaster:558/add-health-checking-of-cosmosdb-database-with-temp-commits#diff-e46dec3a44f968e8ef02c389844be644R13-R17)).

**Is it valuable to add this somehow? And if so, how?**

**Does this PR introduce a user-facing change?**:
Yes, it adds a new optional parameter to the `AddCosmosDb()` DI configuration method. We might want to start using the "options pattern". I'm referring to, for example the `.AddRavenDB()` DI configuration method that allows you to pass in an [`Action<RavenDBOptions> setup`](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/991b5cba1f8dfcc835cac934576fea691a2f1f6a/src/HealthChecks.RavenDB/DependencyInjection/RavenDBHealthCheckBuilderExtensions.cs#L29) to setup all the details for the health check.

We might also want to do that for the `.AddCosmosDb()` DI configuration method (and perhaps keep a backwards compatible overload for the old situation).

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [X] Code compiles correctly
- [ ] Created/updated tests
  - See above for discussion / questions to the reviewer
- [X] Unit tests passing
- [ ] End-to-end tests passing
  - Similar to point 2, see above
- [ ] Extended the documentation
  - I haven't found any pages where the CosmosDb health check is documented, so nothing extended. I'm happy to add some documentation for this, if you can give me some pointers.
- [ ] Provided sample for the feature
  - I've used a new ASP.NET Core project, and configured that to connect to the CosmosDB emulator to test this feature, see above

### CODE REVIEW

**Comment by sungam3r** [comment]
> Yes, it adds a new optional parameter to the AddCosmosDb()

Ok, but breaking change in health check ctor. Consider to add new ctor instead modifying existing.

**Comment by tiesmaster** [comment]
@sungam3r I considered your suggestion, and put back the previous ctor, and chained that to the new one. I hope that's ok.

Next, I also marked the PR ready for review, since based on your feedback, it seems to me we don't want to add any additional things to this PR (like any additional testing, or documentation).

**Comment by tiesmaster** [comment]
@sungam3r If you have a change to look over this PR, I'd definitely appreciate that. If you're busy, or on holidays, then I understand that this takes a bit longer. I'll be on holidays for 3 weeks, starting next weekend, so then any feedback will be processed only in September.

**Comment by sungam3r** [comment]
Anyway I have no access to merge PRs )

**Comment by tiesmaster** [comment]
@sungam3r Thnx for the approval. I see. Who should I ping as well, for this PR? @unaizorrilla perhaps?

**Comment by sungam3r** [comment]
Yes, @CarlosLanderas as well.

**Comment by unaizorrilla** [comment]
Hi,

Thanks for contribute this 

We are on vacation right now, let some days to check and review

**Comment by unaizorrilla** [comment]
I'm working on it!! 

Thanks for your patience!

**Comment by tiesmaster** [comment]
No worries, I was on holiday as well ;) I hope you had a good holiday.

I'm back now, and ready for additional questions, or feedback.

**Comment by unaizorrilla** [comment]
Hi  @tiesmaster 

Merged on master, thanks for contribute. A new release build is on app veyor, when finished a new package will be on NuGet with version 3.1.2

**Pull request merged**
