### PR TITLE
Allow to add config.json to docker

### PR DESCRIPTION
**Pull request by michaelmairegger**
By allowing the user to map a config.json file from outside the docker container into the application the user can configure the application using a json file instead of environment variables

    - 'HealthChecksUI:HealthChecks:0:Name=HTTP-Api-Basic'
    - 'HealthChecksUI:HealthChecks:0:Uri=http://host.docker.internal:5001/health'

He can write the classical way like in appsettings.json:

    {
      "HealthChecksUI": {
        "HealthChecks": [
          {
            "Name": "HTTP-Api-Basic",
            "Uri": "http://host.docker.internal:5001/health"
          }
        ],
        ...
    }

Note: this PR is untested, since the docker image will not compile on my maschine regarding some old node version required for this to buid.

### CODE REVIEW

**Comment by sungam3r** [comment]
conflicts

**Comment by michaelmairegger** [comment]
Conflicts resolved. For this change the docker image must be rebuilt
But as said, I couln't test it because on my maschine building he docker image does not work. But there shouldn't be any issues

**Comment by sungam3r** [comment]
@michaelmairegger How these changes can be verified on CI?

**Comment by michaelmairegger** [comment]
@sungam3r I will test on my machine as I have seen the docker image on master branch is building again. I will keep you informed

**Comment by michaelmairegger** [comment]
I can confirm that this modification works. I don't know how to test it in CI since this requires the docker image to be up and running.

If you test it locally you can do it by mounting a folder containing a config.json file with the following content to `/config` folder

{
  "HealthChecksUI": {
    "HealthChecks": [
      {
        "Name": "HTTP-Api-Basic",
        "Uri": "ENTER_HERE_AN_URL_THAT_RETURNS_HEALTH_DATA"
      }
    ]
  }
}


docker run --volume=FOLDER_CONTAINING_CONFIG_JSON:/config:ro xabarilcoding/healthchecksui:latest

> To make the docker image work, you need to build it on this branch. Note: The docker image does build only after merging the master branch into this branch

**Pull request merged**
