### PR TITLE
Add SmbCifs HealthCheck Project

### PR DESCRIPTION
**Pull request by nunorelvao**

### CODE REVIEW

**Comment by nunorelvao** [comment]
@unaizorrilla , can you please merge this one so i can create after the next pull request?

**Comment by CarlosLanderas** [comment]
@nunorelvao I'm going to review and test the PR to merge it. Could you address the merge problems derived from merging previous PR's?

Thanks

**Comment by nunorelvao** [comment]
@CarlosLanderas , thanks for thereview , i have completed the merge and fixed the problems everything is building , i have another one that first i would like to PR but i will wait for all this to be merged into master so i can also update my fork.

**Comment by CarlosLanderas** [comment]
@nunorelvao I've tested this with BasicAuth using Linux Manjaro Samba and it's working good. How did you test the extended auth integration?

**Comment by nunorelvao** [comment]
> @nunorelvao I've tested this with BasicAuth using Linux Manjaro Samba and it's working good. How did you test the extended auth integration?

Sincerelly i did not tested or use this, i just added because it is documented on SMBCifs plugin:
http://sharpcifsstd.dobes.jp/#howtouse

**Pull request closed without merging**
