### PR TITLE
At LivessTable.tsx for HealthCheck.UI project there image source error

### PR DESCRIPTION
**Pull request by kursatarslan**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Please reference the issue this PR will close: #_[issue number]_

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] Code compiles correctly
- [ ] Created/updated tests
- [ ] Unit tests passing
- [ ] End-to-end tests passing
- [ ] Extended the documentation
- [ ] Provided sample for the feature

### CODE REVIEW

**Comment by CarlosLanderas** [comment]
We are running this in production without issue and this image is embedded in the assembly. Could you share a picture of the UI and the browser console messages?

**Comment by kursatarslan** [comment]
image


➜  healtcheck dotnet --list-sdks
3.1.201 [/usr/local/share/dotnet/sdk]


console.log

vendors-dll.js:22 TypeError: Cannot read property 'image' of undefined
    at t.LivenessTable.getDiscoveryServiceImage (healthchecks-bundle.js:12)
    at healthchecks-bundle.js:12
    at Array.map (<anonymous>)
    at t.LivenessTable.render (healthchecks-bundle.js:12)
    at wo (vendors-dll.js:22)
    at So (vendors-dll.js:22)
    at li (vendors-dll.js:22)
    at di (vendors-dll.js:22)
    at Ji (vendors-dll.js:22)
    at Ii (vendors-dll.js:22)
Co @ vendors-dll.js:22
healthchecks-bundle.js:12 TypeError: Cannot read property 'image' of undefined
    at t.LivenessTable.getDiscoveryServiceImage (healthchecks-bundle.js:12)
    at healthchecks-bundle.js:12
    at Array.map (<anonymous>)
    at t.LivenessTable.render (healthchecks-bundle.js:12)
    at wo (vendors-dll.js:22)
    at So (vendors-dll.js:22)
    at li (vendors-dll.js:22)
    at di (vendors-dll.js:22)
    at Ji (vendors-dll.js:22)
    at Ii (vendors-dll.js:22)
(anonymous) @ healthchecks-bundle.js:12

**Comment by CarlosLanderas** [comment]
Thanks!. let me take a look!. What UI version are you using?

**Comment by kursatarslan** [comment]
I tried to test your github code and got this error when i try to run the sample codes there(HealthChecks.UIAndApi) and I thought that  the dotnet version may have affected but I have not yet download other versions

**Comment by CarlosLanderas** [comment]
UIAndApi is working nice for me. No errors anyway. Are you configuring k8s discovery service into the sample?. Have you tried the nuget package instead of building it  yourself?. 

image

**Comment by kursatarslan** [comment]
Today I tries new version 3.1.1 and got a same error. 
➜  Kursat node --version
v14.3.0
➜  Kursat dotnet --list-sdks

3.1.201 [/usr/local/share/dotnet/sdk]


image

image

image

**Comment by CarlosLanderas** [comment]
@kursatarslan you are not using or have configured the k8s discovery service right?

Thanks

**Comment by kursatarslan** [comment]
No, I don't have  configured the k8s discovery service, Can you send me how to configure the kubernetes service

**Comment by unaizorrilla** [comment]
Hi @CarlosLanderas 

Are you following this?

**Comment by CarlosLanderas** [comment]
@kursatarslan I have tested the UIAndApi sample project in Windows and Ubuntu and I am not able to reproduce your problem.

image


Could you upload to github your project so I can test it?

**Pull request closed without merging**
