### PR TITLE
Feature/improve seq publisher

### PR DESCRIPTION
**Pull request by GustavoFonsecaDeAlmeida**
Implementing a visual improvement to the event in the seq
**What this PR does / why we need it**:
No
**Which issue(s) this PR fixes**:
No
Please reference the issue this PR will close: #_[issue number]_

**Special notes for your reviewer**:

image

**Does this PR introduce a user-facing change?**:

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [ ] Created/updated tests
- [x] Unit tests passing
- [x] End-to-end tests passing
- [ ] Extended the documentation
- [x] Provided sample for the feature

### CODE REVIEW

**Comment by GustavoFonsecaDeAlmeida** [comment]
@unaizorrilla , @CarlosLanderas can review ?

**Comment by unaizorrilla** [comment]
Let me a couple of days to review this, thanks for contribute!

**Comment by GustavoFonsecaDeAlmeida** [comment]
GN!! Any news about ?

**Comment by unaizorrilla** [comment]
I'm working on it!! 

Thanks for your patience!

**Comment by unaizorrilla** [comment]
Merged!

thanks @GustavoFonsecaDeAlmeida  for contribute this. A new release build is on appveyor, when finished a new package 3.2.0 will be available on NuGet!

**Pull request merged**
