### PR TITLE
Add option to configure Azure Service Token Provider for Key Vault check

### PR DESCRIPTION
**Pull request by DaleMittleman**
Giving the developer the opportunity to provide connection string and azure AD instance parameters for the Azure Service Token Provider used by the Key Vault Client

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @DaleMittleman 
I like the PR, let me a couple of days in order to review and merge ( i start my vacation right now)

**Comment by hansmbakker** [comment]
@unaizorrilla @Xabaril this PR is required to be able to connect to KeyVaults using a `User Assigned Identity` (instead of a `System Assigned Identity`).

Is there a chance that you will publish an update to the NuGet package using this PR?

**Comment by sungam3r** [comment]
@DaleMittleman Please rebase onto `master` if you are going to continue work on this PR.

**Comment by sungam3r** [comment]
ping @DaleMittleman

**Comment by sungam3r** [comment]
@DaleMittleman  Do you intend to continue working on that PR?

**Comment by sungam3r** [comment]
@marioleed Maybe you can help with this? You posted PRs for Azure Service Bus project. I think that you may be familiar with Azure Key Vault as well.

**Comment by marioleed** [comment]
@sungam3r Latest code is using a TokenCredential, so I don't think this PR's changes should be used anymore. Should probably close it.

**Comment by sungam3r** [comment]
OK.

Closed due to lack of feedback from @DaleMittleman .

**Pull request closed without merging**
