### PR TITLE
Add Milvus client health check  #2214

### PR DESCRIPTION
**Pull request by smnsht**
**What this PR does / why we need it**:
Add health check for the Milvus client:

**Which issue(s) this PR fixes**:
 Add Milvus client health check

Please reference the issue this PR will close: #2214

**Special notes for your reviewer**:
I am not sure about functional tests - for now they are skipped.
Should I add Milvus image to docker-compose?

**Does this PR introduce a user-facing change?**:
No

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [*] Code compiles correctly
- [*] Created/updated tests
- [*] Unit tests passing
- [*] End-to-end tests passing
- [ ] Extended the documentation
- [ ] Provided sample for the feature

### CODE REVIEW

**Comment by Alirexaa** [comment]
@adamsitnik, Do we need more overload same as other health checks?

**Comment by Alirexaa** [comment]
@smnsht, could you add `Milvus` to `labeler.yml` and also add `healthchecks_milvus.yaml` same as other actions?

**Comment by smnsht** [comment]
@Alirexaa 
I've created 3 workflow files & updated labeler.yml

I have to add milvus docker image to `healthchecks_milvus_ci.yml` - not done yet. I'm checking how I can verify GitHub workflow (unfamiliar to me).

**Comment by Alirexaa** [comment]
> @Alirexaa I've created 3 workflow files & updated labeler.yml
> 
> I have to add milvus docker image to `healthchecks_milvus_ci.yml` - not done yet. I'm checking how I can verify GitHub workflow (unfamiliar to me).

You can see an example below:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/65ab619b0e5dcf27940a1a6baf13cc1ad4f79903/.github/workflows/healthchecks_elasticsearch_ci.yml


Also for passing the functional test you need to add milvus container to the actions.
example:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/65ab619b0e5dcf27940a1a6baf13cc1ad4f79903/.github/workflows/healthchecks_elasticsearch_ci.yml#L31-L36

**Comment by smnsht** [comment]
@Alirexaa 
I've added services from the official docker compose file to my workflow.
(https://milvus.io/docs/install_standalone-docker-compose.md)

This docker compose has been tested in my local environment - it looks good. Functional tests passed.

**Comment by smnsht** [comment]
@Alirexaa 
Done with GitHub workflow. Tested on my personal account - looks good.

**Review by Alirexaa — APPROVED** [review]

**Comment by Alirexaa** [comment]
LGTM. Thanks @smnsht

**Comment by unaizorrilla** [comment]
Probably we need to add a property to version.props for this new packages

**Pull request merged**
