### PR TITLE
use webpack5 syntax to include woff2 in bundle

### PR DESCRIPTION
**Pull request by schulz3000**
**Which issue(s) this PR fixes**: #2130 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: no

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [ ] Created/updated tests
- [x] Unit tests passing
- [x] End-to-end tests passing
- [ ] Extended the documentation
- [ ] Provided sample for the feature

### CODE REVIEW

**Comment by markmonster** [comment]
@schulz3000 looks a good solution. However it seems you have to agree to the Contributor License Agreement before this PR can continue.

**Comment by douglasg14b** [comment]
Can this move forward? This is a pretty important breakage in .Net 8 since the icons are a core part of the UI experience.

**Comment by lucashby** [comment]
> Can this move forward? This is a pretty important breakage in .Net 8 since the icons are a core part of the UI experience. Is it allowed to re-implement this PR?

It would be great if this could move forward.  Is there a community standard around wait time for the CLA?  Can someone else do the PR if no word is received on it?

**Comment by markmonster** [comment]
I think it would be wise to try re-implement this PR. I'm on it.

**Comment by Alirexaa** [comment]
closed this as completed via https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2217

**Pull request closed without merging**
