### PR TITLE
Modernised the Azure Blob, Queue and Table packages

### PR DESCRIPTION
**Pull request by kieronlanning**
**What this PR does / why we need it**:
Breaks the dependency on the old Windows.Azure.Storage package.

**Which issue(s) this PR fixes**:
N/A, partially #408 

Please reference the issue this PR will close: #_[issue number]_

**Special notes for your reviewer**:
Table API is incoming: https://github.com/Azure/azure-sdk-for-net/issues/10176

**Does this PR introduce a user-facing change?**:
No.

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [ ] Created/updated tests
- [x] Unit tests passing
- [x] End-to-end tests passing
- [ ] Extended the documentation
- [ ] Provided sample for the feature

### CODE REVIEW

**Comment by kieronlanning** [comment]
This is updating an existing feature, so the tests, documentation and samples already exist.

**Comment by CarlosLanderas** [comment]
Thanks! This is something we had to do. Requested by some users.

**Comment by kieronlanning** [comment]
No probs.

**Comment by unaizorrilla** [comment]
Hi @kieronlanning 

I try to review this ASAP, thanks for this, as @CarlosLanderas  say, this is requested by some users...

**Comment by kieronlanning** [comment]
@unaizorrilla Hopefully just resolved that odd usings conflict.

**Comment by unaizorrilla** [comment]
Merged, thanks for contribute this @kieronlanning.

A release build is on appveyor, when finished a new release 3.2.1 will be available. Because the dependencies changes I upgrade version to 3.2.X!

**Comment by kieronlanning** [comment]
Nice, thanks for all your hard work @unaizorrilla!

**Pull request merged**
