### PR TITLE
Show 'data' field of HealthChecks in UI

### PR DESCRIPTION
**Pull request by danielcweber**
**What this PR does / why we need it**:

Currently, the 'data' field of HealthChecks is neither stored in the database nor is it shown in the UI. This PR is a step towards storing and showing the data field.

**Which issue(s) this PR fixes**:

Partly solves #718

Here's what it looks like:

image

Co-credit to @MariuszKogut

### CODE REVIEW

**Comment by derSchtefan** [comment]
@danielcweber   re: #718 You showed the UI component for this, was this ever taken into the main branch, it does not show up in my UI.

**Comment by NicolasKlaas** [comment]
Actually have the same question as @derSchtefan how to enable the data dictionary in the UI?

**Comment by NicolasKlaas** [comment]
Actually have the same question as @derSchtefan how to enable the data dictionary in the UI?

**Comment by mathlizee** [comment]
@danielcweber I'm curious as to why you choose to close the pull request. Was it because there was an issue with the modifications you proposed? If not, could it be reopened?

I really think this feature would be appreciated by anyone using the package. I still can't figure out why showing the data from the health check is not currently supported, since it seems to be an essential feature needed to investigate an unhealthy health check!

**Comment by danielcweber** [comment]
There was no issue with the modifications, as a matter of fact, we are running a build from a fork and are happy with it. The PR became conflicted without any feedback, so closing it seemed like the clean way to move forward.

**Comment by SkinnySackboy** [comment]
Is there any chance this could be resurrected?

**Pull request closed without merging**
