### PR TITLE
extended rabbitMq health check with tls option.

### PR DESCRIPTION
**Pull request by hansehe**
The rabbitMq health check was missing tls option, thus it would be useless in many cases where tls with rabbitMq is enabled.

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @hansehe 

The changes contains new parameter on RabbitMQHealthCheck but the extension method for registering the health check don't use this new parameter.

How the user can set the SSL option when the healthcheck is registered?

Also, increment the version for this package on dependencies.props

**Comment by unaizorrilla** [comment]
Hi @hansehe 

Can you address the changes for this PR?

**Comment by hansehe** [comment]
Hi, and I'm sorry for being so slow to reply. I missed the extensions class and the version update, but it should all be fine now. Please have a look at the update, and tell me if something should be changed.

**Comment by unaizorrilla** [comment]
Thanks @hansehe for contribute this, merged and release build enqueued, when finish a new packages version (2.2.1) will be on nuget.

**Pull request merged**
