### PR TITLE
UI page header title now configurable

### PR DESCRIPTION
**Pull request by MCKanpolat**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Please reference the issue this PR will close: #501 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ x] Code compiles correctly
- [ ] Created/updated tests
- [ ] Unit tests passing
- [ ] End-to-end tests passing
- [ ] Extended the documentation
- [ x] Provided sample for the feature

### CODE REVIEW

**Comment by CarlosLanderas** [comment]
@MCKanpolat  thank you very much for your PR!. Could you add a functional test to check the rendered title is changed?

**Comment by gabrielmaldi** [comment]
@MCKanpolat, thanks for this! Do you have plans to add a test as Carlos requested? If you don't have the time, I can submit a new PR based on this one that also includes the test and of course crediting you. Let me know 😄.

**Comment by MCKanpolat** [comment]
> @MCKanpolat, thanks for this! Do you have plans to add a test as Carlos requested? If you don't have the time, I can submit a new PR based on this one that also includes the test and of course crediting you. Let me know 😄.

Hello @gabrielmaldi , I'm a little bit busy these days. If you have a time you can do. 👍🏻 
Thanks

**Comment by gabrielmaldi** [comment]
Done! #731

**Comment by sungam3r** [comment]
Closed in favor of #731.

**Pull request closed without merging**
