### PR TITLE
Initialize UriHealthCheckOptions lazilly

### PR DESCRIPTION
**Pull request by jnovick**
* Improves ability to test applications using the URI health check
* Improves ability to use NSwag client generators with URI health checks

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @jnovick 

Some tests are failing, can you check these errors?

**Comment by jnovick** [comment]
Yes, I will take a look.

**Comment by CarlosLanderas** [comment]
@jnovick, Any update on this? 
Thanks!

**Comment by jnovick** [comment]
When I initially looked, I could not find anything wrong which frustrated me. I just looked again and got the tests running locally and they all pass. I merged master in and it seems to be fine with appveyor as well. I think the test failure before must have either been a fluke or unrelated. Thank you for your follow up reminder since i had forgotten about it.

**Comment by jnovick** [comment]
@unaizorrilla If you have a chance, please take a look.

**Comment by unaizorrilla** [comment]
> When I initially looked, I could not find anything wrong which frustrated me. I just looked again and got the tests running locally and they all pass. I merged master in and it seems to be fine with appveyor as well. I think the test failure before must have either been a fluke or unrelated. Thank you for your follow up reminder since i had forgotten about it.

Appveyor fail sometimes when test external uri's!! I'm working on this PR right now!

**Comment by unaizorrilla** [comment]
Merged, thanks @jnovick  for contribute!!!!

**Pull request merged**
