### PR TITLE
AsideMenuOpened feature

### PR DESCRIPTION
**Pull request by kdaveid**
We use HealthChecksUI as a monitor (big screen in OPS) for our different environments (DEV, INT, STAGE, PROD). The left hand menu uses up a lot of space and could be closed initially. 

Would that be a big issue for you? 

Thanks! 
Best regards, David

### CODE REVIEW

**Comment by CarlosLanderas** [comment]
hello @kdaveid. Thanks for the Pull request.

I'm not sure this is the desired behaviour. I asked to some of my partners using the UI and they prefer having it opened as it does not take much space.

Maybe the best way of achieving this is using a C# settings within the UI settings and set and AsideMenuOpened option.

image

**Comment by kdaveid** [comment]
Hi @CarlosLanderas 
Thanks for your fast answer. Ok, I see your point.
Is this feature (AsideMenuOpened) already there? I have not much knowledge about React but I could try to implement this.

**Comment by CarlosLanderas** [comment]
Don't worry. I can implement it as soon as I return from vacation

**Comment by kdaveid** [comment]
Enjoy your vacation!!

**Comment by kdaveid** [comment]
Ok tried to implement this. Please check PR again :-)
One thing to check especially is: In C# I used a boolean for the toggle but in JS I'm passing/replacing it as a string. There will be a implicit conversion. You may want to change this (or have me changing it). 

Aaaand: I haven't had the time for testing it. 😬

**Comment by CarlosLanderas** [comment]
@kdaveid, the PR is not working. The C# string is being to the frontend as "False" or "True" in string format. This should be a lower case boolean. I fix these minor issues and merge it.

**Comment by CarlosLanderas** [comment]
I have no permission in your branch. Give me permissions if you can or make this PR work with the changes I specified above.

Thanks!

**Comment by kdaveid** [comment]
@CarlosLanderas: You should be Collaborator on my repo now.

**Comment by kdaveid** [comment]
I updated in `UIResourceExtensions` as following: 
```
 .Replace(Keys.HEALTHCHECKSUI_ASIDEMENUEOPENED_TARGET, options.AsideMenuOpened.ToString().ToLower());
```
But, it's still a string because from C# we're manipulating a string. Should I change the HTML/js part too by removing the double quotes?

**Comment by CarlosLanderas** [comment]
> I updated in `UIResourceExtensions` as following:
> 
> ```
>  .Replace(Keys.HEALTHCHECKSUI_ASIDEMENUEOPENED_TARGET, options.AsideMenuOpened.ToString().ToLower());
> ```
> 
> But, it's still a string because from C# we're manipulating a string. Should I change the HTML/js part too by removing the double quotes?

Exactly. The HTML should be a boolean:

```js
 <script type="text/javascript">
        var uiEndpoint = "#apiPath#";
        var webhookEndpoint = "#webhookPath#";
        var asideMenuOpened = #asideMenuOpened#;
   </script>
```

**Comment by kdaveid** [comment]
Done, waiting for Appveyor build

**Comment by kdaveid** [comment]
Should be ok now! Can you test? Sorry for that.

**Comment by CarlosLanderas** [comment]
@kdaveid tested, working and merged. Thanks for your PR!

**Pull request merged**
