### PR TITLE
Uniform conversion for all datetime.

### PR DESCRIPTION
**Pull request by DennisLarsen**
hi, thx for providing healthchecks code.

We have an error, only in our Docker/Rancher environment as this: 'Unknown Date' with no exception or details. This is not true json, witch have the side effect, that all logning is disgarded.
 

`
21.5.2019 14.03.13{"Timestamp":"2019-05-21T12:03:13.0745532+00:00","Level":"Information","MessageTemplate":"Executed DbCommand ({elapsed}ms) [Parameters=[{parameters}], CommandType='{commandType}', CommandTimeout='{commandTimeout}']{newLine}{commandText}","Properties":{"elapsed":"0","parameters":"@p1='?', @p0='?'","commandType":"Text","commandTimeout":30,"newLine":"\n","commandText":"UPDATE \"HealthCheckExecutionEntries\" SET \"Duration\" = @p0\nWHERE \"Id\" = @p1;\nSELECT changes();","EventId":{"Id":20101,"Name":"Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted"},"SourceContext":"Microsoft.EntityFrameworkCore.Database.Command","Scope":["HealthReportCollector is collecting health checks results."]}}
21.5.2019 14.03.13{"Timestamp":"2019-05-21T12:03:13.0843973+00:00","Level":"Debug","MessageTemplate":"HealthReportCollector has completed.","Properties":{"SourceContext":"HealthChecks.UI.Core.HostedService.HealthCheckReportCollector","Scope":["HealthReportCollector is collecting health checks results."]}}
21.5.2019 14.03.13{"Timestamp":"2019-05-21T12:03:13.0844621+00:00","Level":"Debug","MessageTemplate":"HealthCheck collector HostedService executed successfully.","Properties":{"SourceContext":"HealthChecks.UI.Core.HostedService.HealthCheckCollectorHostedService"}}
**Unknown Date**
`
Since I dont know, what timezone our environment is using and sqlite dont have datetime. 
We beleave that missing convertion for datetime i missing and may be the root of your error.

I have tryed to test the code, but have not had any success in doing that in our environment witch will include jenkins, push to docker, running in rancher.

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @DennisLarsen 

Sorry for delay on review this PR :-( .. I try to merge ASAP ( probably on Wednesday )

**Comment by DennisLarsen** [comment]
@unaizorrilla thx, that would be great.

**Comment by DennisLarsen** [comment]
Hi @unaizorrilla 
Is it possible to expedite this matter. i'm a little bit desperate :)

**Comment by unaizorrilla** [comment]
I will merge this today

**Comment by DennisLarsen** [comment]
Thx

**Comment by unaizorrilla** [comment]
Hi @DennisLarsen 

Thanks for your patience, already merged on master. 
A new tag 2.2.29 is building on Appveyor, when finish will be a new package version available on NuGet.

**Comment by DennisLarsen** [comment]
thx. I have updated the package in our project. It did not solve the unknown data issue, so I will try to trace it.

**Pull request merged**
