### PR TITLE
Update Mongo.Driver to 3.0.0

### PR DESCRIPTION
**Pull request by rohitvipin**
**What this PR does / why we need it**:
- Doesn’t currently work when used with 3.0.0

**Which issue(s) this PR fixes**:

Please reference the issue this PR will close: #_[issue number]_

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [ ] Created/updated tests
- [x] Unit tests passing
- [x] End-to-end tests passing
- [ ] Extended the documentation
- [ ] Provided sample for the feature

### CODE REVIEW

**Review by ytsiupiak-ecw — APPROVED** [review]

**Comment by Kiechlus** [comment]
Could a maintainer approve this? This is blocking us currently.

**Comment by VSUT-se** [comment]
Same issue on my side ...

**Comment by peterkiss1** [comment]
@ytsiupiak-ecw @rchaidez-cricut please check on the failure here, the target framework for the package must be changed in order to be compatible with the v3 MongoDB driver.

**Comment by eerhardt** [comment]
I put up an alternate PR using the same approach we are using in .NET Aspire (see [RabbitMQ.Client v7 breaks Aspire.RabbitMQ.Client component (dotnet/aspire#3956)](https://github.com/dotnet/aspire/issues/3956) for the high-level description of the strategy being employed).

[Add support for MongoDB.Driver version 3 (Xabaril/AspNetCore.Diagnostics.HealthChecks#2324)](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2324)

The idea is to support MongoDB.Driver version 2 and version 3 for a while, until users are off of version 2 (or it is out of support).

**Comment by rohitvipin** [comment]
Closing this as there is an alternative one open to support both. 
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2324

**Pull request closed without merging**
