### PR TITLE
use existing connection multiplexer for redis

### PR DESCRIPTION
**Pull request by Sonic198**
**What this PR does / why we need it**:
According to documentation Redis connection should be reused across application.

**Which issue(s) this PR fixes**:
#1773 

Please reference the issue this PR will close: 
#_[1773]_

**Does this PR introduce a user-facing change?**:
Yes.

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ x] Code compiles correctly
- [ x] Created/updated tests
- [ x] Unit tests passing
- [ x] End-to-end tests passing

### CODE REVIEW

**Comment by Sonic198** [comment]
Is there any problem with this PR?

**Comment by sungam3r** [comment]
Just a lack of time for all things. I see all the changes and follow the edits.

**Comment by esskar** [comment]
This is highly needed.

**Comment by rob-baldwin** [comment]
LGTM

**Comment by Sonic198** [comment]
Hi, any additional checks/reviews are needed to get this merged ;)?

**Comment by Sonic198** [comment]
@sungam3r @rob-baldwin could you guys merge this, please?

**Comment by sungam3r** [comment]
Will be reviewed soon and published in v7.

**Comment by sungam3r** [comment]
@Sonic198 Thanks. Sometimes it so happens that review of even simple things is delayed for months. I had a break in the OSS, now I'm starting to return to the support of part of the projects that I abandoned.

**Pull request merged**
