### PR TITLE
 Added support for the expansion of environment variables in HealthCheckDatabaseConnectionString.

### PR DESCRIPTION
**Pull request by mikevanoo**
Added support for the expansion of environment variables in HealthCheckDatabaseConnectionString.

See #95 
@unaizorrilla

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @mikevanoo 
Look well! can you increment dependencies.props UI package version?

**Comment by mikevanoo** [comment]
@unaizorrilla Done.

**Comment by unaizorrilla** [comment]
Thanks @mikevanoo 

I check some cases and publish new tag to create the new packages.

**Comment by unaizorrilla** [comment]
Release build on appveyor, a new package 2.2.13 will be on nuget when release build finish.

**Pull request merged**
