### PR TITLE
Fix connections leak in RabbitMQHealthCheck

### PR DESCRIPTION
**Pull request by Vladimirezh**
**What this PR does / why we need it**:
Every call of healthcheck create new connection. Connection doesn't close. 

**Which issue(s) this PR fixes**:

Please reference the issue this PR will close: #_[issue number]_

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
No

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [x] Created/updated tests
- [x] Unit tests passing
- [x] End-to-end tests passing

### CODE REVIEW

**Comment by Vladimirezh** [comment]
@dotnet-policy-service agree

**Comment by unaizorrilla** [comment]
Hi @Vladimirezh 

Let me some days to review.

**Comment by unaizorrilla** [comment]
Hi @Vladimirezh 

Thanks for submit this PR, just a few notes

- Just tested the current code on sample app HealthChecks.Sample with Rabbit and just one connection is created and the health check is reused always using the uri and options overloads
- You can register your connection and connection factory on the container and use the proper extension method to alternate registration method

**Comment by Vladimirezh** [comment]
To reproduce leak modify ConfigureServices of HealthChecks.Sample to:
```
  //Custom rabbitmq factory
        services.AddSingleton<Func<IConnection>>(() =>
        {
            var factory = new ConnectionFactory
            {
                Uri = new Uri("amqp://localhost:5672"),
                AutomaticRecoveryEnabled = true,
                UseBackgroundThreadsForIO = true
            };

            return factory.CreateConnection();
        });


        services
            .AddApplicationInsightsTelemetry()
            .AddHealthChecks()
            // .AddRabbitMQ(rabbitConnectionString: "amqp://localhost:5672", name: "rabbit1"); //<- Work fine
            .AddRabbitMQ((sp, options) =>
                options.Connection = sp.GetRequiredService<Func<IConnection>>()()); //<- Leak
```
After call route /healthz many times look to Rabbit Management UI
image

**Comment by unaizorrilla** [comment]
Hi @Vladimirezh 

Just curious about your code.. some notes...

If you registered the IConnection as a Singleton and use the overload you mention like this

```csharp
       
        var connectionFactory = new ConnectionFactory
        {
            Uri = new Uri("amqp://localhost:5672")
        };

        services.AddSingleton<IConnection>(connectionFactory.CreateConnection());

        services
            .AddHealthChecks()
            .AddRabbitMQ((sp, options) =>
                options.Connection = sp.GetRequiredService<IConnection>(), name: "rabbit1");
```

just one connection is used 

image


Why you need to register a Func of IConnection?

**Comment by Vladimirezh** [comment]
I have custom connection factory. Factory doesn't implement IConnectionFactory. In example it's Func, in my project it's library abstraction. I use overload with setup and set connection to options.

**Comment by sungam3r** [comment]
@Vladimirezh Proposed changes will not work for multiple registrations. You register RabbitMQHealthCheck as singleton in method accepting user defined `Action<RabbitMQHealthCheckOptions>? setup`/`Action<IServiceProvider, RabbitMQHealthCheckOptions>? setup`, `name`, etc. Second and all other registrations will fetch the latest registered `RabbitMQHealthCheck` from ServiceProvider. This is a well-known design flaw and codebase tends to avoid such usages although you still can find such code in some health checks (alas).

If you look in the code in `master` then you'll see that `RabbitMQHealthCheck` caches connections in static dictionary by options instance as as key. I think that the real problem here - calling `Action<IServiceProvider, RabbitMQHealthCheckOptions>? setup` inside `HealthCheckRegistration`. Other overload with `Action<RabbitMQHealthCheckOptions>? setup` calls it outside - one time. Why so? Because ServiceProvider is available only inside `HealthCheckRegistration` delegate so user-defined delegate is called each time. I agree that options should be changed (initialized) only once. In our overload it's initialized deferred and not once. Please check #2153. It should fix that issue. If OK I would like you to make subsequent PR with all your tests.

ping @adamsitnik It seems to me that we have similar problems with some other checks. Did you fix this with Npgsql or was there something else? I still have not returned to the full support of the project, so I have not studied your changes.

**Pull request closed without merging**
