### PR TITLE
Add EventStore health check using connection string. 

### PR DESCRIPTION
**Pull request by MuadDib**
Clarify that existing check uses URI.

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @MuadDib 

Why not only one HealthCheck? You can create a connection string using uri /login / pass also and use the same healthcheck?

**Comment by MuadDib** [comment]
Heya Unai,

Thanks for your feedback.

My thought process was:
- I don't wanna change any of the existing logic (thus not altering the existing EventStoreHealthCheck class)
- I didn't want to parse connectionString manually (to extract URI/login details) as I want to future proof it if EventStore client ever changes the format
- There is already Create method on EventStore client that takes connectionString
- Follow the same code conventions that are already in place (e.g. AzureServiceBus already has multiple health checks)

Let me know if you would like me to explain myself in more details or if I misunderstood something.

Best,
Igor

**Comment by unaizorrilla** [comment]
Hi @MuadDib 

- AzureServiceBus exist different health checks for different purposes (queue, topics etc) in this case both are for the same "element" EventStore.
- You can mantain back compatibility with new registration methods but with only one health check.

Sounds ok for you?

**Comment by sungam3r** [comment]
@MuadDib  Please rebase onto `master` if you are going to continue work on this PR.

**Comment by sungam3r** [comment]
ping @MuadDib

**Comment by sungam3r** [comment]
@NielsPilgaard are you interested in?

**Comment by NielsPilgaard** [comment]
Version 6.0.2 already uses connection string. If I'm reading this issue correctly, it can be closed as completed.

**Comment by sungam3r** [comment]
Thanks.

**Pull request closed without merging**
