### PR TITLE
Added hangfire server check

### PR DESCRIPTION
**Pull request by pajzo**
Make it possible to check the number of Hangfire servers/instances registered.

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Let me some days to check this, thanks for contribute again!

**Comment by unaizorrilla** [comment]
Some notes:

- You need to update dependencies.props package version every time you change any package.
- Why different healthchecks? Why not a configuration options to specify the task failed or   the numer of servers to be alive?

**Comment by pajzo** [comment]
> * You need to update dependencies.props package version every time you change any package.

Sorry, i didnt know that, i will fix that :)

> * Why different healthchecks? Why not a configuration options to specify the task failed or   the numer of servers to be alive?

I started that way, but I was not sure what was best practice. I will refactor so there is only one health check for Hangfire, but with multiple checks inside depending on the given options.

**Comment by pajzo** [comment]
@unaizorrilla I updated the PR - let me know if something can be improved or is wrong. Also i was not sure if this was a minor og patch versioning bump?

**Comment by unaizorrilla** [comment]
Merged, i do some minor changes.. version is 2.2.1, 2.2 is related with dependency healthchecks!

**Pull request merged**
