### PR TITLE
Add beforeOpen action to SqlServerHealthCheck

### PR DESCRIPTION
**Pull request by JoeSainsburys**
**What this PR does / why we need it**:
Adds a beforeOpen action to SqlServerHealthCheck.cs This allows consumers to do things like pass access tokens to SQL and use Managed Identities.

**Which issue(s) this PR fixes**:

Please reference the issue this PR will close: #150 

**Special notes for your reviewer**:

Added test may not be in the correct place. The implementation of SqlServerHealthCheck does not seem to be tested, I just wanted to test it. Feel free to move/remove test.

**Does this PR introduce a user-facing change?**:

Adds some overloads/optional parameters.

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [x] Created/updated tests
- [x] Unit tests passing
- [ ] End-to-end tests passing - they didn't pass on my machine to begin with - please can someone confirm they pass now?
- [ ] Extended the documentation - N/A? Let me know where to document it and I'll add it
- [ ] Provided sample for the feature - N/A? Let me know where to document it and I'll add it

### CODE REVIEW

**Review by inkel — APPROVED** [review]
This LGTM! Thank you @JoeSainsburys for taking the time to write this PR!

**Comment by MAOliver** [comment]
@JoeSainsburys @inkel Is there something we could do to this to make it pull your token provider from the DI Container?

e.g.             

Parameter to the 2nd constructor in the healthcheckbuilderextension:

 Func<IServiceProvider, Action<SqlConnection>> beforeOpen = default):

Call to the 2nd constructor from the first constructor:

            return builder.AddSqlServer(_ => connectionString, healthQuery, name, failureStatus, tags, timeout, _ => beforeOpen);

And in the Startup.cs:

                    beforeOpen: sp => async conn => conn.AccessToken = await sp.GetRequiredService<IDBAuthTokenService>().GetTokenAsync().ConfigureAwait(false)               

I know that's a little clunky and confusing, but it seems like having it pull the tokenprovider from the service provider would be a good idea...

**Comment by JoeSainsburys** [comment]
@MAOliver we certainly could - but I'm not sure if we want to (it's up to the maintainers really.) Basically what we have now is a hook for doing something to the SqlConnection, so it's very generic at the moment. If we just had an interface like IDBAuthTokenService then it is up to the developer to provide the implementation so it is still pretty generic and wouldn't require any additional nuget packages etc. I don't mind either way @inkel ?

**Comment by inkel** [comment]
Sorry for the long delay. I think that the easiest, the better, at least for a first iteration. Having the before open hook gives the user enough room to execute any other kind of actions besides setting the auth token. If you open the door to add an `IDBAuthTokenService` then you also a can of worms for adding any other kind of interfaces that are injected via DI. In any case, if I were to add DI for this, I'd make it to accept an `SqlConnection` instead.

**Comment by MAOliver** [comment]
Sorry, I wasn't looking for the IDBAuthTokenService -- I would just like some kind of implementation that allows you to pull some kind of token factory out of the DI container (as the connection string provider does). I think, if I'm not mistaken, that the AzureTokenProvider uses a cache that would be shared between request contexts, so, it's not a huge issue if it's implemented as is.

Thanks.

**Comment by JoeSainsburys** [comment]
I was about to knock up a quick example of how I see this being used and I get what you mean now. Do you mean essentially changing the signature of beforeOpen to Action<IServiceProvider, SqlConnection> ? If so then yes I can see how that would be helpful.

**Comment by JoeSainsburys** [comment]
Also please can someone address:

> End-to-end tests passing - they didn't pass on my machine to begin with - please can someone confirm they pass now?

Can I tick these two off?

>  Extended the documentation - N/A? Let me know where to document it and I'll add it
>  Provided sample for the feature - N/A? Let me know where to document it and I'll add it

And I'm not sure what your release cadence looks like but might we be able to get this in to the next release please?

**Comment by unaizorrilla** [comment]
Hi @JoeSainsburys 

I',m reviewing this right now!

**Comment by unaizorrilla** [comment]
Merged!

A new release build is on appveyor, when finished a new package 3.2.0 for SqlServer will be available!

**Comment by JoeSainsburys** [comment]
Brilliant, thank you :smiley:

**Comment by MAOliver** [comment]
@JoeSainsburys Sorry I'm late in responding. Yeah, that's kind of what I was thinking. We'll make it work either way, the internal caching for the tokenprovider makes it less necessary an issue. Thanks for contributing the fix, sir : )

**Pull request merged**
