### PR TITLE
initial go at adding it as a task

### PR DESCRIPTION
**Pull request by carlowahlstedt**
First attempt at #237. I'm not familiar with how to use JSONPath and got stuck, so decided it best to get a first review for continuing on. Let me know if you agree with the direction here and any ideas/pointers you have.

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @lfraile  can you take a look on this PR?

**Comment by sungam3r** [comment]
@carlowahlstedt Is it still actual?

**Comment by carlowahlstedt** [comment]
Going to be honest. I'm so far away from this at this point that I barely remember what this was about.

**Comment by sungam3r** [comment]
OK. That happens.

**Pull request closed without merging**
