### PR TITLE
Update MongoDB.Driver Package Version To 2.28.0

### PR DESCRIPTION
**Pull request by Alirexaa**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Please reference the issue this PR will close: #2265

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] Code compiles correctly
- [ ] Created/updated tests
- [ ] Unit tests passing
- [ ] End-to-end tests passing
- [ ] Extended the documentation
- [ ] Provided sample for the feature

### CODE REVIEW

**Review by adamsitnik — COMMENTED** [review]
Based on https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2265#issuecomment-2250408487 it seems that we should be able to sign the library now. Could you please remove the following line?

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/da7f3a489f89a339c70084fdd5cc3f00a8c6a2c4/src/HealthChecks.MongoDb/HealthChecks.MongoDb.csproj#L8

Thank you @Alirexaa !

**Comment by adamsitnik** [comment]
> it seems that we should be able to sign the library now.

@eerhardt this will allow for signing the Aspire package as well. But I can not find `SignAssembly` in the Aspire repo. Does it mean you have given up on the signing?

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @Alirexaa !

**Comment by eerhardt** [comment]
> > it seems that we should be able to sign the library now.
> 
> @eerhardt this will allow for signing the Aspire package as well. But I can not find `SignAssembly` in the Aspire repo. Does it mean you have given up on the signing?

We just ignore the signing warning in our repo:

https://github.com/dotnet/aspire/blob/d8369e0d6e579127fd47681342b96e14e057df9a/src/Components/Aspire.MongoDB.Driver/Aspire.MongoDB.Driver.csproj#L9

```
    <NoWarn>$(NoWarn);CS8002</NoWarn> <!-- MongoDB packages are not signed -->
```

**Comment by Jaben** [comment]
Any ETA for when this will be released? Thanks!

**Comment by Alirexaa** [comment]
@unaizorrilla we need a new release here.

**Comment by ledouxpl** [comment]
@adamsitnik Could you please prioritize releasing the patch? It's currently preventing us from updating the MongoDB C# driver in our organization without having to take down the health checks.

**Pull request merged**
