### PR TITLE
MongoDB - Fix Unhealthy if no collections exists in the specified database

### PR DESCRIPTION
**Pull request by ThumNet**
**What this PR does / why we need it**:
We are experiencing unhealthy checks if a specified mongo database has no collections yet.

```
System.InvalidOperationException: Sequence contains no elements at System.Linq.ThrowHelper.ThrowNoElementsException() at System.Linq.Enumerable.First[TSource](IEnumerable`1 source) at MongoDB.Driver.IAsyncCursorExtensions.FirstAsync[TDocument](IAsyncCursor`1 cursor, CancellationToken cancellationToken) at HealthChecks.MongoDb.MongoDbHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken) in /_/src/HealthChecks.MongoDb/MongoDbHealthCheck.cs:line 43
```

**Which issue(s) this PR fixes**:
#617

**Special notes for your reviewer**:
None

**Does this PR introduce a user-facing change?**:
No

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [x] Created/updated tests
- [x] Unit tests passing
- [ ] End-to-end tests passing
- [ ] Extended the documentation
- [ ] Provided sample for the feature

### CODE REVIEW

**Review by sungam3r — APPROVED** [review]

**Comment by sungam3r** [comment]
Thanks.

**Comment by sungam3r** [comment]
@ThumNet One test failed. I think `mongoClient.GetDatabase(_specifiedDatabase)` returns an instance event for non existing database so `First()` method correctly failed HC before. I'm fine using `FirstOrDefault` but of course some other changes are required to fix failed test.

**Comment by ThumNet** [comment]
> 

Looking into the failing test, will update the PR when fixed.

**Comment by ThumNet** [comment]
After looking into the failing test, which is called `be_unhealthy_on_connectionstring_specified_database_if_mongodb_is_available_and_database_exist`. 

I think that this test should NOT exists, because of the way mongodb works. MongoDB only creates the database when you first store data in that database. This data could be a [collection](https://docs.mongodb.com/manual/reference/glossary/#std-term-collection) or a [document](https://docs.mongodb.com/manual/reference/glossary/#std-term-document).

 Sources: [official mongo docs](hhttps://www.mongodb.com/basics/create-database#option-2) and [blog post](https://theholmesoffice.com/how-to-create-a-mongodb-database/)

So you agree the test can be removed?

**Comment by sungam3r** [comment]
I've read provided links. Do you think the current method of checking the state of MongoDB is sufficient? I have no experience with MongoDB.

**Comment by ThumNet** [comment]
Instead of getting the collections i think it is better to implement a ping to the database. [Others](https://stackoverflow.com/questions/28835833/how-to-check-connection-to-mongodb) also recommend this.

I will change the code to allow this and update the PR. Also change the test accordingly.

**Comment by ThumNet** [comment]
@sungam3r Update has just been pushed.

**Comment by sungam3r** [comment]
@ThumNet Thanks.

**Pull request merged**
