### PR TITLE
Add configurable default seq input level

### PR DESCRIPTION
**Pull request by GustavoFonsecaDeAlmeida**
**What this PR does / why we need it**:
This PR adds the possibility to configure a writing level to the seq other than information as a default. This helps because in some companies / projects it can occur the creation of monitoring with different levels of writing. Example: You can configure a lower data retention for verbose level logs that the health check logs are in.

**Which issue(s) this PR fixes**:
None
Please reference the issue this PR will close: #_[issue number]_

**Special notes for your reviewer**:
image

**Does this PR introduce a user-facing change?**:
No
Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [ ] Created/updated tests
- [x] Unit tests passing
- [x] End-to-end tests passing
- [ ] Extended the documentation
- [x] Provided sample for the feature

### CODE REVIEW

**Comment by GustavoFonsecaDeAlmeida** [comment]
I kept the default value as information for those who already use it do not suffer a behavior change

**Comment by GustavoFonsecaDeAlmeida** [comment]
@unaizorrilla  , @CarlosLanderas  can review ?

**Comment by ThiagoBarradas** [comment]
Hello guy! I need this feature too!

All SEQ notification flow (for my company) uses log level as a filter parameter. Your contribution will be amazing to me!

Can someone give us a feedback about this PR approval?

Best regards

**Comment by unaizorrilla** [comment]
I'm working on it!! 

Thanks for your patience!

**Pull request merged**
